
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LEOZI
 */
public class Adm extends javax.swing.JFrame {

   private Connection conexao;
    private PreparedStatement pst;
    private ResultSet rs;
    public Adm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        generosField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        usuarioField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sexoField = new javax.swing.JTextField();
        senhaField = new javax.swing.JPasswordField();
        admField = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 603, 370, 90));

        generosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generosFieldActionPerformed(evt);
            }
        });
        getContentPane().add(generosField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 320, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Sexo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Generos Preferidos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Acesso:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, -1, -1));
        getContentPane().add(nomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 320, 30));

        usuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 320, 30));
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 320, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        sexoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(sexoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 320, 30));

        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 320, 30));

        admField.setText("Admin");
        admField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admFieldActionPerformed(evt);
            }
        });
        getContentPane().add(admField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tela_quatro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                 

    try {
        // Obtenha a conexão usando o método conector() da classe ModuloConexao
        this.conexao = ModuloConexao.conector();

        if (this.conexao != null) { // Certifique-se de que a conexão foi estabelecida com sucesso

            // Construa a consulta SQL para inserir um novo usuário
            String sql = "INSERT INTO Usuarios (nome_usuario, senha_usuario, sexo_usuario, email_usuario, genero_pref, nivel_acesso, apelido_usuario) VALUES (?, ?, ?, ?, ?, ?, ?)";
            pst = this.conexao.prepareStatement(sql);

            // Preencha os parâmetros da consulta com os valores do formulário
            pst.setString(1, nomeField.getText());
            pst.setString(2, senhaField.getText());
            pst.setString(3, sexoField.getText());
            pst.setString(4, EmailField.getText());
            pst.setString(5, generosField.getText());
            pst.setString(6, "comum");  // Defina o nível de acesso padrão como "comum"
            pst.setString(7, usuarioField.getText());

            // Execute a inserção
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso");

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados", "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário", "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        // Fechar recursos, se necessário
        try {
            if (pst != null) {
                pst.close();
            }
            // Não feche a conexão aqui, pois ela será usada em outras partes do código
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void generosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generosFieldActionPerformed

    private void sexoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoFieldActionPerformed

    private void admFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admFieldActionPerformed

    private void usuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioFieldActionPerformed

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailField;
    private javax.swing.JRadioButton admField;
    private javax.swing.JTextField generosField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomeField;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JTextField sexoField;
    private javax.swing.JTextField usuarioField;
    // End of variables declaration//GEN-END:variables
}
